### ISSUE TITLE
Not able to read Y And Z columns from CSV?

### ISSUE THREAD

**Issue by Maverick1182** [bastianilso/blender-csv-importer#3]
Hi there,

I may have a very basic problem in that even trying to import you sampledata csv, I get all ten data points but they appear to only have the X coordinates define? 

Is there a setting that I've missed? 

I'm running blender v2.82.7

**Comment by bastianilso** [comment]
Hi Maverick,

When you import the sample data with default settings, the settings in the right-hand side of the CSV import dialog by default has "Animate" checkbox checked - which animates the Y and Z axis from 0 to the desired number. Try unchecking the "Animate" checkbox.

Did that solve the problem for you?

**Comment by Maverick1182** [comment]
Hi, yes. Perfectly.

Thanks!
